######################## production configuration ####################
# The base URL of your site (required). This will be prepended to all relative URLs.
baseURL: "https://www.modsecurity.org/"
googleAnalytics: 
enableRobotsTXT: true
build:
  writeStats: true

# Services
params:
  services:
    matomoAnalytics:
      id: "4"
      url: "piwik.netnea.com/matomo"